spring:
  application:
    name: ezy-payment-application-backend

  mongodb:
    uri: mongodb://admin:admin@localhost:27017/mongo_api?authSource=admin

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  card-encryption-key: "V4YfXK7M7DpAeLq5j1mJ3eXxJq+zWvHcYz3mR8N9pQ0="