spring:
  application:
    name: ezy-payment-application-backend

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/ezy-payment?authSource=admin

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  card-encryption-key: "V4YfXK7M7DpAeLq5j1mJ3eXxJq+zWvHcYz3mR8N9pQ0="


webhooks:
  max-attempts: 5
  retry-delay-ms: 30000